description: Web3 Summit 2019.
name: summit2019
version: v0.1.0
apiVersion: v2
dependencies:
- name: mariadb
  version: 7.3.12
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mariadb.enabled
  tags:
    - wordpress-database
- name: phpmyadmin
  version: 4.3.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mariadb.enabled
