version: 2

jobs:
  buildImage:
    docker:
      - image: web3f/ci-commons:v0.1.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/summit2019 .

workflows:
  version: 2
  test-deploy:
    jobs:
      - buildImage:
          filters:
            branches:
              only: /master/
