{{ if ne .Values.environment "ci" }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "summit2019.namespace" . }}
spec:
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
  {{ include "summit2019.dnsNames" .}}
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      {{ include "summit2019.dnsNames" .}}
{{ end }}
