{{ if ne .Values.environment "ci" }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: phpmyadmin
  namespace: default
spec:
  secretName: phpmyadmin-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - {{ include "summit2019.phpmyadminDnsName" .}}
{{ end }}
