{{ if ne .Values.environment "ci" }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "summit2019.namespace" . }}
spec:
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - {{ include "summit2019.dnsName" .}}
{{ end }}
