{{ if ne .Values.environment "ci" }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: phpmyadmin
  namespace: default
spec:
  secretName: phpmyadmin-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - {{ include "summit2019.phpmyadminDnsName" .}}
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - {{ include "summit2019.phpmyadminDnsName" .}}
{{ end }}
