apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "summit2019.namespace" . }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        name: {{ .Release.Name }}
        volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]
        ports:
        - name: http
          containerPort: {{ .Values.port }}
      - image: nginx:1.7.9
        name: {{ .Release.Name }}-nginx
        volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: app-config-volume
          mountPath: /var/www/html/.env
          subPath: .env
      volumes:
      - name: app-config-volume
        configMap:
          name: {{ .Release.Name }}-app
      - name: nginx-config-volume
        configMap:
          name: {{ .Release.Name }}-nginx
      - name: shared-files
        {{- if eq .Values.environment "ci" }}
        emptyDir: {}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-app
          namespace: {{ include "summit2019.namespace" . }}
        {{- end }}
