apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "summit2019.namespace" . }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        name: {{ .Release.Name }}
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: app-config-volume
          mountPath: /app/.env
          subPath: .env
        ports:
        - name: http
          containerPort: {{ .Values.port }}
        resources:
          requests:
            memory: 512Mi
            cpu: 300m
      volumes:
      - name: app-config-volume
        configMap:
          name: {{ .Release.Name }}-app
      - name: nginx-config-volume
        configMap:
          name: {{ .Release.Name }}-nginx
