apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "summit2019.namespace" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  tls:
  - hosts:
      - {{ include "summit2019.dnsName" . }}
    secretName: {{ .Release.Name }}-tls
  - hosts:
      - {{ include "summit2019.phpmyadminDnsName" . }}
    secretName: phpmyadmin-tls
  rules:
  - host: {{ include "summit2019.dnsName" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.port }}
  - host: {{ include "summit2019.phpmyadminDnsName" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: phpmyadmin
          servicePort: 80
