apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-phpmyadmin
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  tls:
  - hosts:
      - {{ include "summit2019.phpmyadminDnsName" . }}
    secretName: phpmyadmin-tls
  rules:
  - host: {{ include "summit2019.phpmyadminDnsName" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: phpmyadmin
          servicePort: 80
