apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: default
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: phpmyadmin
