apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "summit2019.namespace" . }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: {{ .Values.port }}
  selector:
    app: {{ .Release.Name }}
